set nocompatible

" Allow backspacing over everything in insert mode.
set backspace=indent,eol,start

set history=200		" keep 200 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set wildmenu		" display completion matches in a status line
set number
set relativenumber

set ttimeout		" time out for key codes
set ttimeoutlen=100	" wait up to 100ms after Esc for special key

" Show @@@ in the last line if it is truncated.
set display=truncate

" Show a few lines of context around the cursor.  Note that this makes the
" text scroll if you mouse-click near the start or end of the window.
set scrolloff=5

" Do incremental searching when it's possible to timeout.
if has('reltime')
  set incsearch
endif

" Do not recognize octal numbers for Ctrl-A and Ctrl-X, most users find it
" confusing.
set nrformats-=octal

" Don't use Ex mode, use Q for formatting.
" Revert with ":unmap Q".
map Q gq

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
" Revert with ":iunmap <C-U>".
inoremap <C-U> <C-G>u<C-U>

" Switch syntax highlighting on when the terminal has colors or when using the
" GUI (which always has colors).
if &t_Co > 2 || has("gui_running")
  syntax on
  let c_comment_strings=1
  set hlsearch
endif

if 1
  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 73,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  " Revert with ":filetype off".
  filetype plugin indent on
endif

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
" Revert with: ":delcommand DiffOrig".
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif

if has('langmap') && exists('+langremap')
  " Prevent that the langmap option applies to characters that result from a
  " mapping.  If set (default), this may break plugins (but it's backward
  " compatible).
  set nolangremap
endif

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
  packadd! matchit
endif

set tabstop=8
set softtabstop=8
set shiftwidth=8
set noexpandtab
set foldmethod=indent

if exists("c_curly_error")
  unlet c_curly_error
endif
let c_no_curly_error=1

noremap <PageUp> <Up>
noremap <PageDown> <Down>
inoremap <PageUp> <Up>
inoremap <PageDown> <Down>
noremap -h :nohl<CR>
noremap -t :tab new<CR>
noremap -x :%!xxd<CR>
noremap -X :%!xxd -r<CR>
noremap <BS> b
noremap \ <BS>
" set langmap=qwfpbjluy\\;;qwertyuiop,arstgmneio;asdfghjkl\\;,zxcdvkh;\\\\zxcvnm,QWFPBJLUY\:;QWERTYUIOP,ARSTGMNEIO;ASDFGHJKL\:,ZXCDVKH;\|ZXCVNM
set nolangremap

set backup
set backupdir=~/vim_backups

